### ISSUE TITLE
Document work stealing

### ISSUE THREAD

**Issue by jasone** [BranchTaken/Hemlock#104]
Document how work stealing fits with executor scheduling algorithms, how mutability/effects tracking enables work stealing, and examples of work stealing both simple and complex.

**Comment by jasone** [comment]
Started in 1de3ac4f0ae2e0c932103db77f1eafb2ac8be2f5.

**Comment by jasone** [comment]
4e074e9a92e57515601d95f07c1cff15fd8b8eca more or less resolves this issue, right?

**Comment by cevans87** [comment]
Correct. While the documentation has a few known holes, the holes are noted in the docs I think it's complete enough to leave alone.
