### ISSUE TITLE
Refactor `Bootstrap.File`

### ISSUE THREAD

**Issue by cevans87** [BranchTaken/Hemlock#157]
The boostrap file API needs to support submission of the following system calls into the executor's ioring instance. The same is true for completion. The completion API should support direct completion, e.g.
```ocaml
let s = File.Read.submit buf file in
let c = File.Read.complete s
```

The file API needs to be build on top of the Submit and Complete API such that it closely matches the following Hemlock API
```hemlock
val File:
    val Read:
        val Error:
            type t

        val Id:
            type t = uns

        val Submit:
            type t
            val id: t -> Id.t

        val Complete:
            type t = result Error.t bytes
            val id: t -> Id.t
            val container_hlt: t >hlt-> _&slice _&bytes

        val submit: uns -> File.t >os-> Submit.t
        val complete: Submit.t -> Complete.t

    val read_hlt: uns -> t >hlt-> _&slice _&bytes
    let read n t = Read.submit n t |> Read.complete |> Read.Complete.container
```

Supported file operations.
- [x] #161
- [x] #162
- [x] #163
- [x] #164
- [x] #165

**Comment by jasone** [comment]
Re: Hemlock syntax, note that currently modules are e.g.

```hemlock
val File:
    val Read:
...
```

The capitalization is what gives them away as modules.

Someday we may have a parser which catches these things. :wink:

**Comment by cevans87** [comment]
> Should we open an issue for receive?
I just started opening one, but realized that I basically duplicated #148.

**Comment by cevans87** [comment]
Notes from a conversation today.

We talked about the safety of providing buffers to `read` and `write`, and decided that we can do a few things at runtime to ensure that only the actor or only the kernel can write to an `IOBuf` at any given moment, but we couldn't come up with a solution that was both simple and didn't have serious drawbacks. For now, we're going to say that developers will need to take care when using an IOBuf that they don't read or write it while submitted to the kernel for work. So, despite the obvious danger in the API, we're not putting guards in place. So, something like the following will be possible.
```hemlock
let buf = IOBuf.init 1024
# set the contents of buf to something...
let submit = File.Write.submit ~buf file
IOBuf.put 0 '\0' buf  # Obviously a concurrent write bug with the kernel.
let complete = File.Write.complete submit
```
