### ISSUE TITLE
Run code through ocp-indent.

### ISSUE THREAD

**Issue by jasone** [BranchTaken/Hemlock#27]
Lots of code has somehow slipped in without proper indentation.  Standardize formatting by running all the code through ocp-indent and manually adjust things like line breaks as necessary to improve overall code consistency.

**Comment by cevans87** [comment]
I also had the thought of creating a github action that shows scary-red and possibly blocks merging PRs so that we're always properly indented.

**Comment by jasone** [comment]
A GitHub action for this would be great.  I'd also like to prohibit trailing whitespace if `ocp-indent` doesn't automatically strip it out.

In a couple places we'll need to change style to make automatic formatting work nicely.  The one I'm currently aware of is

```ocaml
(*******************************************************************************
 * Begin tests.
 *)
```
The last line's leading whitespace is stripped by `ocp-indent`.

This indents as expected:

```ocaml
(******************************************************************************)
(* Begin tests. *)
```

**Comment by jasone** [comment]
I suggest we tackle this as soon as we have #8, #25, and #39 integrated.

**Comment by cevans87** [comment]
Another thought I have is that we might want two separate actions for ocp-indent. One for pull_requests and one that's periodically run on master or based on new code being committed to master.

I think it'd be best if a pull_request ocp-indent action just catches funny problems in the lines added or modified by the current PR. If there happen to be indentation problems already in master, this action wouldn't block us from committing new, clean code.

For the periodic/on_merge to master action, I think ocp-indent could just run on everything and show a status that we do or don't have indentation problems in master.

**Comment by jasone** [comment]
Actually, #8 and #39 aren't blockers for this issue, so go ahead.

**Comment by jasone** [comment]
I think our happy steady state is code that `ocp-indent` makes no changes to.  But as you say, if you write the action to only complain about formatting issues in changes, then we can make the transition incrementally with minimal friction even if other changes are intermingled.  Presumably once we do a full manual pass and commit the formatting changes, it will never again be necessary to consider formatting issues outside of changes.
